package com.junhangxintong.chuanzhangtong.gen;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.junhangxintong.chuanzhangtong.shipposition.bean.ShipDetailsBean;

import com.junhangxintong.chuanzhangtong.gen.ShipDetailsBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shipDetailsBeanDaoConfig;

    private final ShipDetailsBeanDao shipDetailsBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shipDetailsBeanDaoConfig = daoConfigMap.get(ShipDetailsBeanDao.class).clone();
        shipDetailsBeanDaoConfig.initIdentityScope(type);

        shipDetailsBeanDao = new ShipDetailsBeanDao(shipDetailsBeanDaoConfig, this);

        registerDao(ShipDetailsBean.class, shipDetailsBeanDao);
    }
    
    public void clear() {
        shipDetailsBeanDaoConfig.clearIdentityScope();
    }

    public ShipDetailsBeanDao getShipDetailsBeanDao() {
        return shipDetailsBeanDao;
    }

}
